### ISSUE TITLE
Please release the new version with fixed nimble file.

### ISSUE THREAD

**Issue by yglukhov** [vegansk/nimfp#5]

**Comment by vegansk** [comment]
Done in 0.2.1

**Comment by vegansk** [comment]
Oops, in 0.2.0 😃

**Comment by yglukhov** [comment]
@vegansk, its not done. 0.2.0 still points at broken nimble file.

**Comment by vegansk** [comment]
Turns out that GitHub doesn't like `git push --tags -f` :-(. Released version 0.2.1
